runtime: go111

handlers:
- url: /api/donations
  script: auto

- url: /favicon.ico
  static_files: dist/justimagineit/favicon.ico
  upload: dist/justimagineit/favicon.ico

- url: /
  static_files: dist/justimagineit/index.html
  upload: dist/justimagineit/index.html

- url: /
  static_dir: dist
